# Generated by Django 4.2.8 on 2023-12-30 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_category_alter_contact_picture_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
    ]
